using AiVideoDetection.Application.Videos.Ai;
using AiVideoDetection.Application.Videos.Interfaces;
using AiVideoDetection.Application.Videos.Options;
using AiVideoDetection.Domain.Enums;
using Microsoft.Extensions.Options;

namespace AiVideoDetection.Infrastructure.Videos.Ai;

public class EvidenceGenerationService(IOptions<ScoringOptions> options) : IEvidenceGenerationService
{
    private readonly ScoringOptions _options = options.Value;

    public IReadOnlyList<CreateEvidenceItemDto> GenerateEvidence(EvidenceGenerationInput input)
    {
        var evidence = new List<CreateEvidenceItemDto>();

        evidence.AddRange(CreateFrameEvidence(input));
        evidence.AddRange(input.MetadataWarnings.Select(CreateMetadataEvidence));

        if (input.ScoringResult.Confidence < 0.55m)
        {
            evidence.Add(new CreateEvidenceItemDto(
                null,
                EvidenceType.ConfidenceNote,
                EvidenceSeverity.Medium,
                "Limited confidence",
                "The result may be less reliable due to limited frames, low confidence, or missing metadata signals.",
                null,
                null));
        }

        if (input.ModelVersion.StartsWith("mock", StringComparison.OrdinalIgnoreCase))
        {
            evidence.Add(new CreateEvidenceItemDto(
                null,
                EvidenceType.SystemNote,
                EvidenceSeverity.Low,
                "Mock AI service result",
                "This analysis was generated by the mock AI service for pipeline integration and should not be treated as a real AI detection result.",
                null,
                null));
        }

        return evidence;
    }

    private IEnumerable<CreateEvidenceItemDto> CreateFrameEvidence(EvidenceGenerationInput input)
    {
        return input.FrameResults
            .Where(frame => frame.AiScore >= _options.MediumFrameScoreThreshold)
            .OrderByDescending(frame => frame.AiScore)
            .Take(Math.Max(_options.MaxFrameEvidenceItems, 1))
            .Select(frame =>
            {
                var severity = frame.AiScore >= _options.HighFrameScoreThreshold
                    ? EvidenceSeverity.High
                    : EvidenceSeverity.Medium;
                var title = severity == EvidenceSeverity.High
                    ? "High AI indicator frame"
                    : "Moderate AI indicator frame";
                input.FrameIdToVideoFrameId.TryGetValue(frame.FrameId, out var videoFrameId);
                return new CreateEvidenceItemDto(
                    videoFrameId == 0 ? null : videoFrameId,
                    EvidenceType.AiFrameScore,
                    severity,
                    title,
                    $"Frame {frame.FrameIndex} at {frame.TimestampSeconds:0.###}s returned score {frame.AiScore:0.###} with confidence {frame.Confidence:0.###}.",
                    frame.AiScore,
                    frame.TimestampSeconds);
            });
    }

    private static CreateEvidenceItemDto CreateMetadataEvidence(string warning)
    {
        var (severity, title, description, impact) = warning switch
        {
            "missing_creation_time" => (EvidenceSeverity.Low, "Missing creation time", "The video metadata does not include a creation timestamp.", 0.20m),
            "missing_encoder" => (EvidenceSeverity.Low, "Missing encoder metadata", "The video metadata does not identify the encoder.", 0.15m),
            "no_audio_stream" => (EvidenceSeverity.Low, "No audio stream detected", "No audio stream was detected in the media metadata.", 0.10m),
            "unusually_low_bitrate" => (EvidenceSeverity.Medium, "Heavy compression indicator", "The media bitrate appears unusually low for the available metadata.", 0.40m),
            "missing_core_metadata" => (EvidenceSeverity.Medium, "Incomplete core metadata", "Some core media metadata could not be read.", 0.35m),
            "unreadable_metadata" => (EvidenceSeverity.High, "Unreadable metadata", "The media metadata could not be read reliably.", 0.55m),
            _ => (EvidenceSeverity.Low, "Metadata warning", $"Metadata warning detected: {warning}.", 0.15m)
        };

        return new CreateEvidenceItemDto(
            null,
            EvidenceType.MetadataWarning,
            severity,
            title,
            description,
            impact,
            null);
    }
}
