// <auto-generated />
using System;
using System.Net;
using AiVideoDetection.Domain.Enums;
using AiVideoDetection.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiVideoDetection.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260731145325_AddPasswordResetTokens")]
    partial class AddPasswordResetTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "analysis_label", new[] { "LikelyReal", "LikelyAiGenerated", "EditedManipulated", "Suspicious", "Inconclusive" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "analysis_segment_status", new[] { "Pending", "Preparing", "Ready", "Analyzing", "Completed", "Failed", "CancelRequested", "Cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "confidence_level", new[] { "Low", "Medium", "High", "Inconclusive" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "evidence_severity", new[] { "Low", "Medium", "High", "Critical" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "evidence_type", new[] { "AiFrameScore", "MetadataWarning", "ProcessingWarning", "ConfidenceNote", "SystemNote" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "job_status", new[] { "Queued", "Preparing", "Processing", "Finalizing", "PauseRequested", "Paused", "ResumeRequested", "Completed", "Failed", "Retrying", "CancelRequested", "Cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "User", "Admin", "Reviewer", "EnterpriseAdmin" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "video_status", new[] { "Uploaded", "Queued", "Processing", "Completed", "Failed", "Cancelled", "Deleted" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.AiProviderRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AiResultId")
                        .HasColumnType("bigint")
                        .HasColumnName("ai_result_id");

                    b.Property<long>("AnalysisJobId")
                        .HasColumnType("bigint")
                        .HasColumnName("analysis_job_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("http_status_code");

                    b.Property<string>("ProviderJobId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_job_id");

                    b.Property<string>("ProviderMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider_mode");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_name");

                    b.Property<string>("ProviderRequestId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_request_id");

                    b.Property<string>("RawRequestMetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_request_metadata_json");

                    b.Property<string>("RawResponseJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_response_json");

                    b.Property<DateTimeOffset?>("RequestCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("request_completed_at");

                    b.Property<DateTimeOffset>("RequestStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("request_started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("status");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("VideoId")
                        .HasColumnType("bigint")
                        .HasColumnName("video_id");

                    b.HasKey("Id");

                    b.HasIndex("AiResultId");

                    b.HasIndex("AnalysisJobId");

                    b.HasIndex("UserId");

                    b.HasIndex("ProviderName", "ProviderJobId")
                        .HasDatabaseName("ix_ai_provider_requests_provider_job");

                    b.HasIndex("VideoId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ai_provider_requests_video_created");

                    b.ToTable("ai_provider_requests", (string)null);
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.AiResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("ExternalCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("external_completed_at");

                    b.Property<decimal?>("ExternalConfidence")
                        .HasColumnType("numeric")
                        .HasColumnName("external_confidence");

                    b.Property<string>("ExternalErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("external_error_message");

                    b.Property<string>("ExternalLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_label");

                    b.Property<string>("ExternalProviderJobId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_provider_job_id");

                    b.Property<string>("ExternalProviderName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_provider_name");

                    b.Property<string>("ExternalProviderResultId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_provider_result_id");

                    b.Property<string>("ExternalProviderStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_provider_status");

                    b.Property<string>("ExternalRawResponseJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("external_raw_response_json");

                    b.Property<DateTimeOffset?>("ExternalRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("external_requested_at");

                    b.Property<decimal?>("ExternalScore")
                        .HasColumnType("numeric")
                        .HasColumnName("external_score");

                    b.Property<string>("FallbackReason")
                        .HasColumnType("text")
                        .HasColumnName("fallback_reason");

                    b.Property<bool>("FallbackUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("fallback_used");

                    b.Property<string>("FinalDecisionSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Local")
                        .HasColumnName("final_decision_source");

                    b.Property<decimal>("FinalScore")
                        .HasColumnType("numeric")
                        .HasColumnName("final_score");

                    b.Property<string>("HybridResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("hybrid_result_json");

                    b.Property<AnalysisLabel>("Label")
                        .HasColumnType("analysis_label")
                        .HasColumnName("label");

                    b.Property<string>("LocalResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("local_result_json");

                    b.Property<decimal?>("MetadataScore")
                        .HasColumnType("numeric")
                        .HasColumnName("metadata_score");

                    b.Property<long?>("ModelVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("model_version_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Local")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("local")
                        .HasColumnName("provider_mode");

                    b.Property<string>("RawModelOutputJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_model_output_json");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("summary");

                    b.Property<decimal?>("TemporalScore")
                        .HasColumnType("numeric")
                        .HasColumnName("temporal_score");

                    b.Property<long>("VideoId")
                        .HasColumnType("bigint")
                        .HasColumnName("video_id");

                    b.Property<decimal>("VisualScore")
                        .HasColumnType("numeric")
                        .HasColumnName("visual_score");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .HasDatabaseName("ix_ai_results_label");

                    b.HasIndex("ModelVersionId")
                        .HasDatabaseName("ix_ai_results_model_version_id");

                    b.HasIndex("Provider")
                        .HasDatabaseName("ix_ai_results_provider");

                    b.HasIndex("VideoId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ai_results_video_id_created");

                    b.ToTable("ai_results", (string)null);
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.AnalysisJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AnalyzedCoverageSeconds")
                        .HasColumnType("numeric")
                        .HasColumnName("analyzed_coverage_seconds");

                    b.Property<bool>("CancelRequested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cancel_requested");

                    b.Property<DateTimeOffset?>("CancelRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancel_requested_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CompletedSegments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("completed_segments");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CurrentStep")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("current_step");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("FailedStage")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("failed_stage");

                    b.Property<DateTimeOffset?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("LastCheckpoint")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_checkpoint");

                    b.Property<int>("MaxRetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("max_retry_count");

                    b.Property<bool>("PauseRequested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("pause_requested");

                    b.Property<DateTimeOffset?>("PauseRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pause_requested_at");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<string>("PausedFromStage")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("paused_from_stage");

                    b.Property<int>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("progress");

                    b.Property<string>("ResumeBackgroundJobId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resume_background_job_id");

                    b.Property<DateTimeOffset?>("ResumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resumed_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("ScanMode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("scan_mode");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<JobStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("job_status")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Queued'::job_status");

                    b.Property<decimal?>("TotalDurationSeconds")
                        .HasColumnType("numeric")
                        .HasColumnName("total_duration_seconds");

                    b.Property<int>("TotalSegments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_segments");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("VideoId")
                        .HasColumnType("bigint")
                        .HasColumnName("video_id");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_analysis_jobs_status");

                    b.HasIndex("VideoId")
                        .IsUnique()
                        .HasDatabaseName("ux_analysis_jobs_one_active_per_video")
                        .HasFilter("status NOT IN ('Completed', 'Failed', 'Cancelled')");

                    b.ToTable("analysis_jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_analysis_jobs_progress", "progress >= 0 AND progress <= 100");
                        });
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.AnalysisSegment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AiScore")
                        .HasColumnType("numeric")
                        .HasColumnName("ai_score");

                    b.Property<long>("AnalysisJobId")
                        .HasColumnType("bigint")
                        .HasColumnName("analysis_job_id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("Duration")
                        .HasColumnType("numeric")
                        .HasColumnName("duration");

                    b.Property<decimal>("EndTime")
                        .HasColumnType("numeric")
                        .HasColumnName("end_time");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<DateTimeOffset?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("LocalTemporaryPath")
                        .HasColumnType("text")
                        .HasColumnName("local_temporary_path");

                    b.Property<int>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("progress");

                    b.Property<string>("ProviderRequestId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_request_id");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<string>("SafeErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("safe_error_message");

                    b.Property<int>("SegmentIndex")
                        .HasColumnType("integer")
                        .HasColumnName("segment_index");

                    b.Property<decimal>("StartTime")
                        .HasColumnType("numeric")
                        .HasColumnName("start_time");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<AnalysisSegmentStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("analysis_segment_status")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Pending'::analysis_segment_status");

                    b.Property<long>("VideoId")
                        .HasColumnType("bigint")
                        .HasColumnName("video_id");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_analysis_segments_status");

                    b.HasIndex("VideoId");

                    b.HasIndex("AnalysisJobId", "SegmentIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_analysis_segments_job_index");

                    b.ToTable("analysis_segments", null, t =>
                        {
                            t.HasCheckConstraint("ck_analysis_segments_progress", "progress >= 0 AND progress <= 100");

                            t.HasCheckConstraint("ck_analysis_segments_times", "end_time > start_time AND duration > 0");
                        });
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.ApiUsageMonthly", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("FailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_count");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_name");

                    b.Property<int>("QuotaLimit")
                        .HasColumnType("integer")
                        .HasColumnName("quota_limit");

                    b.Property<int>("RequestCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("request_count");

                    b.Property<int>("SuccessCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("success_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("ProviderName", "Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("ux_api_usage_monthly_provider_year_month");

                    b.ToTable("api_usage_monthly", (string)null);
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.EvidenceItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AiResultId")
                        .HasColumnType("bigint")
                        .HasColumnName("ai_result_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<decimal?>("ScoreImpact")
                        .HasColumnType("numeric")
                        .HasColumnName("score_impact");

                    b.Property<EvidenceSeverity>("Severity")
                        .HasColumnType("evidence_severity")
                        .HasColumnName("severity");

                    b.Property<decimal?>("TimestampSeconds")
                        .HasColumnType("numeric")
                        .HasColumnName("timestamp_seconds");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<EvidenceType>("Type")
                        .HasColumnType("evidence_type")
                        .HasColumnName("type");

                    b.Property<long?>("VideoFrameId")
                        .HasColumnType("bigint")
                        .HasColumnName("video_frame_id");

                    b.HasKey("Id");

                    b.HasIndex("AiResultId")
                        .HasDatabaseName("ix_evidence_items_ai_result_id");

                    b.HasIndex("Severity")
                        .HasDatabaseName("ix_evidence_items_severity");

                    b.HasIndex("VideoFrameId")
                        .HasDatabaseName("ix_evidence_items_video_frame_id");

                    b.ToTable("evidence_items", (string)null);
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.FrameHash", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ahash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("dhash");

                    b.Property<long>("FrameId")
                        .HasColumnType("bigint")
                        .HasColumnName("frame_id");

                    b.Property<string>("HashVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("mvp-v1")
                        .HasColumnName("hash_version");

                    b.Property<string>("PHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("phash");

                    b.Property<long>("VideoId")
                        .HasColumnType("bigint")
                        .HasColumnName("video_id");

                    b.HasKey("Id");

                    b.HasIndex("AHash")
                        .HasDatabaseName("ix_frame_hashes_ahash");

                    b.HasIndex("DHash")
                        .HasDatabaseName("ix_frame_hashes_dhash");

                    b.HasIndex("PHash")
                        .HasDatabaseName("ix_frame_hashes_phash");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("ix_frame_hashes_video_id");

                    b.HasIndex("FrameId", "HashVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_frame_hashes_frame_id_hash_version");

                    b.ToTable("frame_hashes", (string)null);
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.JobLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("step_name");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_job_logs_job_id_created");

                    b.ToTable("job_logs", (string)null);
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.MetadataResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AudioCodec")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("audio_codec");

                    b.Property<long?>("Bitrate")
                        .HasColumnType("bigint")
                        .HasColumnName("bitrate");

                    b.Property<string>("Codec")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codec");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<decimal?>("DurationSeconds")
                        .HasColumnType("numeric")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("Encoder")
                        .HasColumnType("text")
                        .HasColumnName("encoder");

                    b.Property<decimal?>("Fps")
                        .HasColumnType("numeric")
                        .HasColumnName("fps");

                    b.Property<bool>("HasMissingMetadata")
                        .HasColumnType("boolean")
                        .HasColumnName("has_missing_metadata");

                    b.Property<string>("RawJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<string>("Resolution")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("resolution");

                    b.Property<long>("VideoId")
                        .HasColumnType("bigint")
                        .HasColumnName("video_id");

                    b.Property<string>("WarningsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("warnings_json");

                    b.HasKey("Id");

                    b.HasIndex("VideoId")
                        .IsUnique()
                        .HasDatabaseName("ux_metadata_results_video_id");

                    b.ToTable("metadata_results", (string)null);
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.ModelVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_model_versions_active");

                    b.HasIndex("Version")
                        .IsUnique()
                        .HasDatabaseName("ux_model_versions_version");

                    b.ToTable("model_versions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Mock deterministic AI scoring model for pipeline integration.",
                            IsActive = true,
                            Name = "Mock Video AI",
                            Version = "mock-video-ai-v1"
                        });
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_password_reset_tokens_token_hash");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_password_reset_tokens_user_created");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<IPAddress>("CreatedByIp")
                        .HasColumnType("inet")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.SourceMatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<ConfidenceLevel>("Confidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("confidence_level")
                        .HasColumnName("confidence")
                        .HasDefaultValueSql("'Medium'::confidence_level");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<decimal?>("DurationMatchScore")
                        .HasColumnType("numeric")
                        .HasColumnName("duration_match_score");

                    b.Property<decimal?>("HashMatchScore")
                        .HasColumnType("numeric")
                        .HasColumnName("hash_match_score");

                    b.Property<decimal?>("MetadataMatchScore")
                        .HasColumnType("numeric")
                        .HasColumnName("metadata_match_score");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("platform");

                    b.Property<int>("Rank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("rank");

                    b.Property<decimal>("SimilarityScore")
                        .HasColumnType("numeric")
                        .HasColumnName("similarity_score");

                    b.Property<decimal?>("SourceCredibilityScore")
                        .HasColumnType("numeric")
                        .HasColumnName("source_credibility_score");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UploadDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upload_datetime");

                    b.Property<string>("UploaderName")
                        .HasColumnType("text")
                        .HasColumnName("uploader_name");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<long>("VideoId")
                        .HasColumnType("bigint")
                        .HasColumnName("video_id");

                    b.HasKey("Id");

                    b.HasIndex("UploadDatetime")
                        .HasDatabaseName("ix_source_matches_upload_datetime");

                    b.HasIndex("VideoId", "Rank")
                        .HasDatabaseName("ix_source_matches_video_rank");

                    b.ToTable("source_matches", null, t =>
                        {
                            t.HasCheckConstraint("ck_source_matches_duration_match_score", "duration_match_score IS NULL OR (duration_match_score >= 0 AND duration_match_score <= 1)");

                            t.HasCheckConstraint("ck_source_matches_hash_match_score", "hash_match_score IS NULL OR (hash_match_score >= 0 AND hash_match_score <= 1)");

                            t.HasCheckConstraint("ck_source_matches_metadata_match_score", "metadata_match_score IS NULL OR (metadata_match_score >= 0 AND metadata_match_score <= 1)");

                            t.HasCheckConstraint("ck_source_matches_similarity_score", "similarity_score >= 0 AND similarity_score <= 1");

                            t.HasCheckConstraint("ck_source_matches_source_credibility_score", "source_credibility_score IS NULL OR (source_credibility_score >= 0 AND source_credibility_score <= 1)");
                        });
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<UserRole>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("user_role")
                        .HasColumnName("role")
                        .HasDefaultValueSql("'User'::user_role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.Video", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal?>("DurationSeconds")
                        .HasColumnType("numeric")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("FileExtension")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("file_extension");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<string>("FormatName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("format_name");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original_name");

                    b.Property<DateTimeOffset?>("RetentionDeleteAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retention_delete_at");

                    b.Property<string>("Sha256Hash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sha256_hash");

                    b.Property<VideoStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("video_status")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Uploaded'::video_status");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Sha256Hash")
                        .HasDatabaseName("ix_videos_sha256_hash");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_videos_status");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_videos_user_created");

                    b.ToTable("videos", (string)null);
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.VideoFrame", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("FrameIndex")
                        .HasColumnType("integer")
                        .HasColumnName("frame_index");

                    b.Property<string>("FrameUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frame_url");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool>("IsKeyframe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_keyframe");

                    b.Property<decimal>("TimestampSeconds")
                        .HasColumnType("numeric")
                        .HasColumnName("timestamp_seconds");

                    b.Property<long>("VideoId")
                        .HasColumnType("bigint")
                        .HasColumnName("video_id");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("ix_video_frames_video_id");

                    b.HasIndex("VideoId", "FrameIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_video_frames_video_id_frame_index");

                    b.ToTable("video_frames", (string)null);
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.AiProviderRequest", b =>
                {
                    b.HasOne("AiVideoDetection.Domain.Entities.AiResult", "AiResult")
                        .WithMany("ProviderRequests")
                        .HasForeignKey("AiResultId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AiVideoDetection.Domain.Entities.AnalysisJob", "AnalysisJob")
                        .WithMany()
                        .HasForeignKey("AnalysisJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiVideoDetection.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiVideoDetection.Domain.Entities.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiResult");

                    b.Navigation("AnalysisJob");

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.AiResult", b =>
                {
                    b.HasOne("AiVideoDetection.Domain.Entities.ModelVersion", "ModelVersion")
                        .WithMany("AiResults")
                        .HasForeignKey("ModelVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AiVideoDetection.Domain.Entities.Video", "Video")
                        .WithMany("AiResults")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelVersion");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.AnalysisJob", b =>
                {
                    b.HasOne("AiVideoDetection.Domain.Entities.Video", "Video")
                        .WithMany("AnalysisJobs")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.AnalysisSegment", b =>
                {
                    b.HasOne("AiVideoDetection.Domain.Entities.AnalysisJob", "AnalysisJob")
                        .WithMany("Segments")
                        .HasForeignKey("AnalysisJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiVideoDetection.Domain.Entities.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisJob");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.EvidenceItem", b =>
                {
                    b.HasOne("AiVideoDetection.Domain.Entities.AiResult", "AiResult")
                        .WithMany("EvidenceItems")
                        .HasForeignKey("AiResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiVideoDetection.Domain.Entities.VideoFrame", "VideoFrame")
                        .WithMany("EvidenceItems")
                        .HasForeignKey("VideoFrameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AiResult");

                    b.Navigation("VideoFrame");
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.FrameHash", b =>
                {
                    b.HasOne("AiVideoDetection.Domain.Entities.VideoFrame", "VideoFrame")
                        .WithMany("FrameHashes")
                        .HasForeignKey("FrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiVideoDetection.Domain.Entities.Video", "Video")
                        .WithMany("FrameHashes")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");

                    b.Navigation("VideoFrame");
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.JobLog", b =>
                {
                    b.HasOne("AiVideoDetection.Domain.Entities.AnalysisJob", "AnalysisJob")
                        .WithMany("Logs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisJob");
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.MetadataResult", b =>
                {
                    b.HasOne("AiVideoDetection.Domain.Entities.Video", "Video")
                        .WithOne("MetadataResult")
                        .HasForeignKey("AiVideoDetection.Domain.Entities.MetadataResult", "VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("AiVideoDetection.Domain.Entities.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("AiVideoDetection.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.SourceMatch", b =>
                {
                    b.HasOne("AiVideoDetection.Domain.Entities.Video", "Video")
                        .WithMany("SourceMatches")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.Video", b =>
                {
                    b.HasOne("AiVideoDetection.Domain.Entities.User", "User")
                        .WithMany("Videos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.VideoFrame", b =>
                {
                    b.HasOne("AiVideoDetection.Domain.Entities.Video", "Video")
                        .WithMany("Frames")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.AiResult", b =>
                {
                    b.Navigation("EvidenceItems");

                    b.Navigation("ProviderRequests");
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.AnalysisJob", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Segments");
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.ModelVersion", b =>
                {
                    b.Navigation("AiResults");
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.User", b =>
                {
                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.Video", b =>
                {
                    b.Navigation("AiResults");

                    b.Navigation("AnalysisJobs");

                    b.Navigation("FrameHashes");

                    b.Navigation("Frames");

                    b.Navigation("MetadataResult");

                    b.Navigation("SourceMatches");
                });

            modelBuilder.Entity("AiVideoDetection.Domain.Entities.VideoFrame", b =>
                {
                    b.Navigation("EvidenceItems");

                    b.Navigation("FrameHashes");
                });
#pragma warning restore 612, 618
        }
    }
}
